@host =http://localhost:3000


### Test end points
GET {{host}}/api/products/rert/trt http/1.1

### Getting all products
GET {{host}}/api/products http/1.1


### Getting a product by id
GET {{host}}/api/products/60c5ab04a8ad5b1c20aed277 http/1.1


### Create a product
POST {{host}}/api/products http/1.1
Content-Type: application/json

{
    "name" : "Macbook Pro3",
    "description" : " Macboob Pro3"
}


### Update a product
PATCH  {{host}}/api/products/60c5ab04a8ad5b1c20aed277 http/1.1
Content-Type: application/json

{
    "name" : "Macbook Pro8"
}

### Delete a product by id
DELETE  {{host}}/api/products/60c5ab04a8ad5b1c20aed277 http/1.1